# Importing Libraries

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix,classification_report

import tensorflow as tf
from tensorflow import keras

c:\Users\yashy\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


# Loading the Dataset

In [2]:
df = pd.read_csv('./data/churn_modelling.csv')

In [3]:
df.shape

(10000, 14)

In [4]:
df.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [5]:
df.tail(3)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [8]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [9]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

# Cleaning

### Dropping unnecessary columns

In [10]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [11]:
df.isna().sum() 

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

No null values

# Separating the Features and the Labels

In [12]:
X=df.iloc[:, :df.shape[1]-1].values 
y=df.iloc[:, -1].values 
X.shape, y.shape

((10000, 10), (10000,))

# Encoding Categorical Data

In [13]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [14]:
country_encoder = LabelEncoder()  # Label Encoder for country

X[:,1] = country_encoder.fit_transform(X[:,1])

This code uses a LabelEncoder to convert categorical data in the second column (country) of the X dataset into numerical values.

In [15]:
gender_encoder = LabelEncoder()  # Label Encoder for gender

X[:,2] = gender_encoder.fit_transform(X[:,2])

This code uses a LabelEncoder to convert categorical data in the third column (gender) of the X dataset into numerical values.

In [16]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

X after encoding 'country' and 'gender'

# Splitting the Database

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Normalize the train and test data

In [18]:
sc=StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

This code is using the StandardScaler from scikit-learn to standardize (normalize) the feature data in a machine learning dataset, separately for the training and testing sets

In [19]:
X_train

array([[ 0.16958176,  1.51919821, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 , -0.89294542,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079,  0.3131264 , -1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [20]:
X_test

array([[-0.55204276,  0.3131264 , -1.09168714, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-1.31490297, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [ 0.57162971,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.74791227,  1.51919821,  0.91601335, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-0.00566991,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-0.79945688,  0.3131264 ,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Initialize & Build the Model

In [21]:
len(X_train[0])

10

In [22]:
classifier = keras.Sequential([
    keras.layers.Dense(32, input_shape=(10,), activation='relu'),  # Hidden Layer 1
    keras.layers.Dense(13, activation='relu'),  # Hidden Layer 2
    keras.layers.Dense(1, activation='sigmoid')  # Output Layer
])

classifier.compile(optimizer='adam',
              loss='binary_crossentropy',  # Generally used for binary classification
              metrics=['accuracy'])

classifier.fit(X_train, y_train, epochs=10)

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.5204 - accuracy: 0.7470
Epoch 2/10
250/250 [==============================] - 1s 5ms/step - loss: 0.4167 - accuracy: 0.8199
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3872 - accuracy: 0.8395
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3663 - accuracy: 0.8482
Epoch 5/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3545 - accuracy: 0.8515
Epoch 6/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3489 - accuracy: 0.8540
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3445 - accuracy: 0.8575
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3409 - accuracy: 0.8583
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3383 - accuracy: 0.8589
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8595

This code defines a neural network model for binary classification using Keras:

The model has three layers: 
an input layer with 10 features,<br> 
two hidden layers with ReLU activation functions, and <br>
an output layer with a sigmoid activation function.

It's compiled with the 'adam' optimizer, 'binary_crossentropy' loss function (common for binary classification), and 'accuracy' as the evaluation metric.

In [23]:
y_pred = classifier.predict(X_test)
y_pred  # Predicted Values

63/63 [==============================] - 0s 1ms/step


array([[0.29428864],
       [0.4430803 ],
       [0.24933617],
       ...,
       [0.13424626],
       [0.11121682],
       [0.11967732]], dtype=float32)

In [24]:
y_pred = (y_pred > 0.5)
y_pred 

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

if y_pred > 0.5 customer will not leave

In [25]:
score = classifier.evaluate(X_train, y_train)  # Classifier score on training set

print("Train Loss:", score[0])
print("Train Accuracy:", score[1])

250/250 [==============================] - 0s 1ms/step - loss: 0.3318 - accuracy: 0.8634
Train Loss: 0.33175182342529297
Train Accuracy: 0.8633750081062317


In [26]:
score = classifier.evaluate(X_test, y_test)  # Classifier score on testing set

print("Test Loss:", score[0])
print("Test Accuracy:", score[1])

63/63 [==============================] - 1s 4ms/step - loss: 0.3425 - accuracy: 0.8645
Test Loss: 0.3424639403820038
Test Accuracy: 0.8644999861717224


# Print the Accuracy Score and Confusion Matrix

In [27]:
cm = confusion_matrix(y_test, y_pred)  # Confusion Matrix
cm

array([[1528,   67],
       [ 204,  201]], dtype=int64)

In [28]:
cr = classification_report(y_test, y_pred)  # Classification Report
print(cr)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.75      0.50      0.60       405

    accuracy                           0.86      2000
   macro avg       0.82      0.73      0.76      2000
weighted avg       0.86      0.86      0.85      2000

